# Generated by Django 5.2.6 on 2025-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtheme',
            name='show',
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='theme',
            field=models.ManyToManyField(to='planetarium.showtheme'),
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
