# Generated by Django 5.2.6 on 2025-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_remove_showtheme_show_astronomyshow_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
