# Generated by Django 5.2.6 on 2025-09-16 15:10

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="showsession",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.movie_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="astronomyshow",
            name="theme",
            field=models.ManyToManyField(
                related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
        migrations.AddConstraint(
            model_name="showsession",
            constraint=models.UniqueConstraint(
                fields=("planetarium_dome", "show_time"), name="unique_session_in_dome"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("show_session", "row", "seat"), name="unique_ticket_per_seat"
            ),
        ),
    ]
